export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const TOKEN_STILL_VALID = "TOKEN_STILL_VALID";
export const LOG_OUT = "LOG_OUT";

export const FETCH_DATES_SUCCESS = "FETCH_DATES_SUCCESS";

export const FETCH_SONGS_SUCCESS = "FETCH_SONGS_SUCCESS";
export const UPVOTE_SONG_SUCCESS = "UPVOTE_SONG_SUCCESS";
export const DOWNVOTE_SONG_SUCCESS = "DOWNVOTE_SONG_SUCCESS";
export const REQUEST_SONG_SUCCESS = "REQUEST_SONG_SUCCESS";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";
